### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by OmeGak** [particlequest/ParticleQuest#6]
We need to start a dev blog. Options we haver are:
- Wordpress instalation.
- Octopress git blog.
# Wordpress

We have more freedom to customize the blog and some cool themes to make it look more professional. On the other hand we need hosting for it.
# Octopress

This option is interesting because the blog is self contained in the git repository. It's not as user friendly as Wordpress and it will require more work to make it look fancy.

**Comment by JJ** [comment]
You can use free hosting  at wordpress.com. It's not too customizable, but it does teh job.

**Comment by OmeGak** [comment]
I've been looking into Octopress and after struggling with Ruby for the first time you can check the result here: [http://omegak.github.com/ParticleQuest/](http://omegak.github.com/ParticleQuest/).

I still need to check how usable it's gonna be, but it looks promising so far. :+1:

**Comment by JJ** [comment]
That's pretty cool!

2012/12/14 Alejandro Avilés notifications@github.com

> I've been looking into Octopress and after struggling with Ruby for the
> first time you can check the result here:
> http://omegak.github.com/ParticleQuest/.
> 
> I still need to check how usable it's gonna be, but it looks promising so
> far. [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/OmeGak/ParticleQuest/issues/6#issuecomment-11394399.

## 

JJ

**Comment by OmeGak** [comment]
We got Octopress running seamlessly. The blog can be accessed at (http://omegak.github.com/ParticleQuest)[http://omegak.github.com/ParticleQuest] meanwhile @jessykate updates the DNSs.
